import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "../contexts/appcontext";
import { AuthProvider } from "../contexts/authcontext";
import { LoaderProvider } from "../contexts/loadercontext";
import SmoothScroll from "../anim/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Projects Task App",
  description: "Generated by Projects Task",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <LoaderProvider>
          <AuthProvider>
            <AppProvider>
              <SmoothScroll>
                {children}
              </SmoothScroll>
            </AppProvider>
          </AuthProvider>
        </LoaderProvider>
      </body>
    </html>
  );
}
